task:
  name: FreeBSD
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    - pkg install -y perl
    - perl -V    
  build_script:
    - perl Makefile.PL
  test_script:    
    - make test


task:
  name: MacOS
  osx_instance:
    image: catalina-xcode-11.3.1
  install_script:
    - perl -V    
  build_script:
    - perl Makefile.PL
  test_script:    
    - make test
