task:
  name: FreeBSD
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  test_script:
    - pkg install -y bash
    - perl -V
    - perl Makefile.PL
    - make test


task:
  name: MacOS
  osx_instance:
    image: catalina-xcode-11.3.1
  test_script:
    - perl -V
    - perl Makefile.PL
    - make test
